# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
---
repos:
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        args:
          # Preview is needed to get automatic string-breaking
          - '--preview'

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
      - id: reorder-python-imports

  - repo: https://github.com/PyCQA/pylint
    rev: v3.0.0a6
    hooks:
      - id: pylint
        additional_dependencies:
          # - "pylint-pytest"
          - "pylint-pydantic"
        args:
          # Load our plugins
          # - '--load-plugins=pylint_pytest'
          - '--load-plugins=pylint_pydantic'
          # Ignore 'import-error' and 'no-name-in-module'
          # As we do not want to install all dependencies under pre-commit
          - '--disable=E0401'
          - '--disable=E0611'
          # Ignore 'wrong-import-order'
          # reorder-python-imports decides the order, if pylint disagrees ¯\_(ツ)_/¯
          - '--disable=C0411'
          # Ignore import related issues in general
          - '--ignore-imports=y'
          # Ignore 'fixme'
          # We allow TODOs in the source code
          - '--disable=W0511'
          # With 5 or more lines of duplicate code, we should refactor it
          - '--min-similarity-lines=5'

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        entry: pflake8
        additional_dependencies: [pyproject-flake8]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.2.0
    hooks:
      - id: mypy
        language: system
        types: [file, python]

  - repo: https://github.com/fsfe/reuse-tool
    rev: v1.1.2
    hooks:
      - id: reuse
