# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0

version: "3.9"
services:
  orggatekeeper:
    build: .
    command: ["uvicorn", "--factory", "app.main:create_app", "--host", "0.0.0.0", "--reload"]
    environment:
      FASTRAMQPI__AMQP__URL: "amqp://guest:guest@msg-broker:5672/"
      FASTRAMQPI__AUTH_SERVER: "http://keycloak:8080/auth"
      FASTRAMQPI__CLIENT_ID: "dipex"
      FASTRAMQPI__CLIENT_SECRET: "603f1c82-d012-4d04-9382-dbe659c533fb"
      FASTRAMQPI__MO_URL: "http://mo:5000"

      SELF_OWNED_IT_SYSTEM_CHECK: "SD_uuid"
      LINE_MANAGEMENT_TOP_LEVEL_UUIDS: '["b6c11152-0645-4712-a207-ba2c53b391ab", "23a2ace2-52ca-458d-bead-d1a42080579f"]'
      HIDDEN: '["a6773531-6c0a-4c7b-b0e2-77992412b610"]'
    networks:
      - os2mo_default
    ports:
      - "8000:8000"
    volumes:
      - ./orggatekeeper:/opt/app/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://amqp_trigger_orggatekeeper:8000/metrics"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 30s
    depends_on:
      init:
        condition: service_completed_successfully

  init:
    image: magentaaps/os2mo-init:2
    environment:
      AUTH_SERVER: "http://keycloak:8080/auth"
      CLIENT_ID: "dipex"
      CLIENT_SECRET: "603f1c82-d012-4d04-9382-dbe659c533fb"
      MO_URL: "http://mo:5000"
    networks:
      - os2mo_default
    volumes:
     - type: bind
       source: ./init.config.yaml
       target: /config/config.yml
       read_only: true

networks:
  os2mo_default:
    external: true
